
---
  - hosts: webserver
    become: true
    tasks:
        - name: install rpms
          yum:
            name: "{{item}}"
            state: present
            update_cache: yes
          with_items:
             - samba
             #- firefox
