---
 - hosts: ansible-webserver
   become: true
   tasks: 
      - service:
          name: nginx
          state: stopped
# - hosts: ansible-webserver
#   become: true
#   tasks:
#     - service:
#          name: mysql
#          state: restarted

 - hosts: ansible-webserver
   become: true
   tasks: 
     - service:
         name: smb
         state: restarted
