---
 - hosts: ansible-webserver
   become: true
   tasks: 
     - name: verify httpd service
       command: service httpd status

     - name: verify httpd is listening on 81 port
       wait_for: port=81 timeout=10
     
     - name: verify nginx service
       command: service nginx status
   
     - name: verify if nginx is listening on port 80
       wait_for: port=80 timeout=10
